/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'id' : string,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Plan {
  'id' : string,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'monthlyPrice' : bigint,
}
export interface Property {
  'id' : string,
  'zip' : string,
  'owner' : Principal,
  'city' : string,
  'state' : string,
  'address' : string,
  'timestamp' : bigint,
}
export interface ServiceRequest {
  'id' : string,
  'status' : string,
  'title' : string,
  'urgency' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'propertyId' : string,
  'updatedAt' : bigint,
  'photos' : Array<string>,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProperty' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createServiceRequest' : ActorMethod<
    [string, string, string, string],
    string
  >,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllPlans' : ActorMethod<[], Array<Plan>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactForm' : ActorMethod<[string], ContactForm>,
  'getPlanById' : ActorMethod<[string], Plan>,
  'getProperty' : ActorMethod<[string], Property>,
  'getServiceRequest' : ActorMethod<[string], ServiceRequest>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string, string], string>,
  'updateServiceRequestStatus' : ActorMethod<[string, string], undefined>,
  'uploadPhoto' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];