/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactForm = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Plan = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'monthlyPrice' : IDL.Nat,
});
export const Property = IDL.Record({
  'id' : IDL.Text,
  'zip' : IDL.Text,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'urgency' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'propertyId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'photos' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProperty' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactForm' : IDL.Func([IDL.Text], [ContactForm], ['query']),
  'getPlanById' : IDL.Func([IDL.Text], [Plan], ['query']),
  'getProperty' : IDL.Func([IDL.Text], [Property], ['query']),
  'getServiceRequest' : IDL.Func([IDL.Text], [ServiceRequest], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateServiceRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactForm = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Plan = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'monthlyPrice' : IDL.Nat,
  });
  const Property = IDL.Record({
    'id' : IDL.Text,
    'zip' : IDL.Text,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'urgency' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'propertyId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'photos' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProperty' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactForm' : IDL.Func([IDL.Text], [ContactForm], ['query']),
    'getPlanById' : IDL.Func([IDL.Text], [Plan], ['query']),
    'getProperty' : IDL.Func([IDL.Text], [Property], ['query']),
    'getServiceRequest' : IDL.Func([IDL.Text], [ServiceRequest], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateServiceRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };